/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(detector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(17867f37e707405fecba12ebe8de8db3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dji_droneid/detector.h>
// pydoc.h is automatically generated in the build directory
#include <detector_pydoc.h>

void bind_detector(py::module& m)
{

    using detector    = gr::dji_droneid::detector;


    py::class_<detector, gr::hier_block2,
        std::shared_ptr<detector>>(m, "detector", D(detector))

        .def(py::init(&detector::make),
           D(detector,make)
        )
        



        ;




}








