/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-dji_droneid
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DJI_DRONEID_API_H
#define INCLUDED_DJI_DRONEID_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_dji_droneid_EXPORTS
#define DJI_DRONEID_API __GR_ATTR_EXPORT
#else
#define DJI_DRONEID_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DJI_DRONEID_API_H */
