/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4384f371a0acd77c255acf790ea502c6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/droneid/decode.h>
// pydoc.h is automatically generated in the build directory
#include <decode_pydoc.h>

void bind_decode(py::module& m)
{

    using decode = ::gr::droneid::decode;


    py::class_<decode,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<decode>>(m, "decode", D(decode))

        .def(py::init(&decode::make), py::arg("debug_path"), D(decode, make))


        ;
}
