/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(time_sync.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a826484d77978013b16512bd464ca13a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/droneid/time_sync.h>
// pydoc.h is automatically generated in the build directory
#include <time_sync_pydoc.h>

void bind_time_sync(py::module& m)
{

    using time_sync = ::gr::droneid::time_sync;


    py::class_<time_sync,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<time_sync>>(m, "time_sync", D(time_sync))

        .def(py::init(&time_sync::make), py::arg("sample_rate"), D(time_sync, make))


        ;
}
